language: node_js

sudo: required

node_js: stable

install:
  - npm install 

branches:
  only:
    - whopro

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install hexo-cli -g

install:
  - cnpm install

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: master
  on:
    branch: whopro